export enum BotPermissionType {
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_CHANNELS = 'MANAGE_CHANNELS',
  SEND_MESSAGES = 'SEND_MESSAGES',
  READ_MESSAGES = 'READ_MESSAGES',
  ATTACH_FILES = 'ATTACH_FILES',
  JOIN_VOICE = 'JOIN_VOICE',
  RECORD_AUDIO = 'RECORD_AUDIO',
  STREAM_SCREEN = 'STREAM_SCREEN',
  MUTE_MEMBERS = 'MUTE_MEMBERS',
  KICK_MEMBERS = 'KICK_MEMBERS',
  CREATE_LESSON = 'CREATE_LESSON',
  CHECK_ATTENDANCE = 'CHECK_ATTENDANCE',
  NOTIFY_CHANNEL = 'NOTIFY_CHANNEL',
}

export enum BotChannelPermissionType {
  CAN_SEE = 'CAN_SEE',
  CAN_WRITE = 'CAN_WRITE',
  CAN_NOTIFY = 'CAN_NOTIFY',
  CAN_JOIN = 'CAN_JOIN',
}

export enum PermissionLevel {
  DENY = 'DENY',
  ALLOW = 'ALLOW',
}
